### ISSUE TITLE
Hook up to TravisCI

### ISSUE THREAD

**Issue by hurrymaplelad** [karma-runner/karma-nodeunit#1]
Who doesn't love testing test glue code?

**Comment by hurrymaplelad** [comment]
@vojtajina Could you please [activate the Github hook](http://about.travis-ci.org/docs/user/getting-started/#Step-two%3A-Activate-GitHub-Service-Hook) or grant me admin access to this repo I can set the hook?

**Comment by vojtajina** [comment]
Sure. Done.
