### ISSUE TITLE
Use nodeunit as a module, thus remove included version

### ISSUE THREAD

**Issue by paazmaya** [karma-runner/karma-nodeunit#5]
Currently nodeunit is included in the project, while it should be used as a module, like any other npm thing...

**Comment by hurrymaplelad** [comment]
I'd love to.  Last I checked, the version of nodeunit published to npm doesn't run in the browser.  You have to [run a make task](https://github.com/caolan/nodeunit/blob/master/Makefile#L23) to get the browser version.  We could use a package.json script like `postinstall`, but that feels overcomplicated...

Discussed a little as option 2 [here](https://github.com/caolan/nodeunit/issues/201).  Probably worth it's own issue on nodeunit.
